version: '3.4'

services:
  app:
    image: ${DOCKER_REGISTRY-}webapplicationlab
    build:
      context: .
      dockerfile: WebApplicationLab/Dockerfile
  app2:
    image: ${DOCKER_REGISTRY-}webapplicationlab
    build:
      context: .
      dockerfile: WebApplicationLab/Dockerfile
  redis:
    container_name: redis-1
    image: redis/redis-stack:latest

  proxy:
    image: nginx:mainline

