version: '3.4'

services:
  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5050:80"
  app2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5051:80"
  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
       
